export const TOP_MANGA_GENRE_ID = 1998;
export const MOST_POPULAR_MANGA_GENRE_ID = 2001;

export const FAVOURITE_TYPE = {
  MANGA: 'FAVOURITE_TYPE_MANGA',
  AUTHOR: 'FAVOURITE_TYPE_AUTHOR',
  CHARACTER: 'FAVOURITE_TYPE_CHARACTER',
};

export const THEME = {
  LIGHT: 'light',
  DARK: 'dark',
};
