export const TOP_MANGA_GENRE_ID = 1998;
export const MOST_POPULAR_MANGA_GENRE_ID = 2001;

export const FAVOURITE_TYPE = {
  MANGA: 'FAVOURITE_TYPE_MANGA',
  AUTHOR: 'FAVOURITE_TYPE_AUTHOR',
  CHARACTER: 'FAVOURITE_TYPE_CHARACTER',
};

export const THEME = {
  LIGHT: 'light',
  DARK: 'dark',
};

export const LANGUAGE = {
  ENGLISH: 'en',
  TURKISH: 'tr',
};

export const MAX_SEARCH_RECENT_COUNT = 5;

export const SEARCH_RECENT = {
  MANGA: 'SEARCH_RECENT_MANGA',
  AUTHOR: 'SEARCH_RECENT_AUTHOR',
  CHARACTER: 'SEARCH_RECENT_CHARACTER',
};

export const CATEGORY_HORIZONTAL_TYPE = {
  MANGA: 'CATEGORY_HORIZONTAL_TYPE_MANGA',
  FAVOURITE_MANGA: 'CATEGORY_HORIZONTAL_TYPE_FAVOURITE_MANGA',
  READING: 'CATEGORY_HORIZONTAL_TYPE_READING',
  FINISHED: 'CATEGORY_HORIZONTAL_TYPE_FINISHED',
  FAVOURITE_AUTHOR: 'CATEGORY_HORIZONTAL_TYPE_FAVOURITE_AUTHOR',
  FAVOURITE_CHARACTER: 'CATEGORY_HORIZONTAL_TYPE_FAVOURITE_CHARACTER',
};

export const CUSTOM_CATEGORY_IDS = {
  READING: -1,
  FINISHED: -2,
  FAVOURITE_MANGA: -3,
  FAVOURITE_AUTHOR: -4,
  FAVOURITE_CHARACTER: -5,
};
